config/routes.rb
Rails.application.routes.draw do
  resources :inscriptions
  get 'home/index'

  get 'home/nao_autorizado'

  get 'home/comprovante'

  post 'home/salvar_inscricao'

  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/inscription.rb
class Inscription < ApplicationRecord

	validates_presence_of :nome, :endereco, :bairro, :local_trabalho, :municipio, :uf, :regime_juridico, :cargo_funcao, :rg, :cpf, :email, :contato, :responsavel
	validates_uniqueness_of :cpf, :rg

	before_save :maiusculas_sem_acentos

  def maiusculas_sem_acentos

    self.nome = ActiveSupport::Inflector.transliterate(self.nome).upcase if !self.nome.blank?

    self.endereco = ActiveSupport::Inflector.transliterate(self.endereco).upcase if !self.endereco.blank?

    self.bairro = ActiveSupport::Inflector.transliterate(self.bairro).upcase if !self.bairro.blank?

    self.local_trabalho = ActiveSupport::Inflector.transliterate(self.local_trabalho).upcase if !self.local_trabalho.blank?

    self.municipio = ActiveSupport::Inflector.transliterate(self.municipio).upcase if !self.municipio.blank?

    self.regime_juridico = ActiveSupport::Inflector.transliterate(self.regime_juridico).upcase if !self.regime_juridico.blank?

    self.cargo_funcao = ActiveSupport::Inflector.transliterate(self.cargo_funcao).upcase if !self.cargo_funcao.blank?

    self.rg = ActiveSupport::Inflector.transliterate(self.rg).upcase if !self.rg.blank?

    self.responsavel = ActiveSupport::Inflector.transliterate(self.responsavel).upcase if !self.responsavel.blank?

  end
end

app/controllers/inscriptions_controller.rb
class InscriptionsController < ApplicationController
  before_action :set_inscription, only: [:show, :edit, :update, :destroy]

  # GET /inscriptions
  # GET /inscriptions.json
  def index
    @inscriptions = Inscription.all
  end

  # GET /inscriptions/1
  # GET /inscriptions/1.json
  def show
  end

  # GET /inscriptions/new
  def new
    @inscription = Inscription.new
  end

  # GET /inscriptions/1/edit
  def edit
  end

  # POST /inscriptions
  # POST /inscriptions.json
  def create
    @inscription = Inscription.new(inscription_params)

    respond_to do |format|
      if @inscription.save
        format.html { redirect_to @inscription, notice: 'Inscription was successfully created.' }
        format.json { render :show, status: :created, location: @inscription }
      else
        format.html { render :new }
        format.json { render json: @inscription.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /inscriptions/1
  # PATCH/PUT /inscriptions/1.json
  def update
    respond_to do |format|
      if @inscription.update(inscription_params)
        format.html { redirect_to @inscription, notice: 'Inscription was successfully updated.' }
        format.json { render :show, status: :ok, location: @inscription }
      else
        format.html { render :edit }
        format.json { render json: @inscription.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /inscriptions/1
  # DELETE /inscriptions/1.json
  def destroy
    @inscription.destroy
    respond_to do |format|
      format.html { redirect_to inscriptions_url, notice: 'Inscription was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_inscription
      @inscription = Inscription.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def inscription_params
      params.require(:inscription).permit(:nome, :endereco, :bairro, :local_trabalho, :municipio, :uf, :regime_juridico, :cargo_funcao, :rg, :cpf, :email, :contato, :responsavel)
    end
end

app/helpers/inscriptions_helper.rb
module InscriptionsHelper
end

app/views/inscriptions/_form.html.erb
<%= form_with(model: inscription, local: true) do |form| %>
  <% if inscription.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(inscription.errors.count, "error") %> prohibited this inscription from being saved:</h2>

      <ul>
      <% inscription.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :nome %>
    <%= form.text_field :nome, id: :inscription_nome %>
  </div>

  <div class="field">
    <%= form.label :endereco %>
    <%= form.text_field :endereco, id: :inscription_endereco %>
  </div>

  <div class="field">
    <%= form.label :bairro %>
    <%= form.text_field :bairro, id: :inscription_bairro %>
  </div>

  <div class="field">
    <%= form.label :local_trabalho %>
    <%= form.text_field :local_trabalho, id: :inscription_local_trabalho %>
  </div>

  <div class="field">
    <%= form.label :municipio %>
    <%= form.text_field :municipio, id: :inscription_municipio %>
  </div>

  <div class="field">
    <%= form.label :uf %>
    <%= form.text_field :uf, id: :inscription_uf %>
  </div>

  <div class="field">
    <%= form.label :regime_juridico %>
    <%= form.text_field :regime_juridico, id: :inscription_regime_juridico %>
  </div>

  <div class="field">
    <%= form.label :cargo_funcao %>
    <%= form.text_field :cargo_funcao, id: :inscription_cargo_funcao %>
  </div>

  <div class="field">
    <%= form.label :rg %>
    <%= form.text_field :rg, id: :inscription_rg %>
  </div>

  <div class="field">
    <%= form.label :cpf %>
    <%= form.text_field :cpf, id: :inscription_cpf %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email, id: :inscription_email %>
  </div>

  <div class="field">
    <%= form.label :contato %>
    <%= form.text_field :contato, id: :inscription_contato %>
  </div>

  <div class="field">
    <%= form.label :responsavel %>
    <%= form.text_field :responsavel, id: :inscription_responsavel %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/inscriptions/edit.html.erb
<h1>Editing Inscription</h1>

<%= render 'form', inscription: @inscription %>

<%= link_to 'Show', @inscription %> |
<%= link_to 'Back', inscriptions_path %>

app/views/inscriptions/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Inscriptions</h1>

<table>
  <thead>
    <tr>
      <th>Nome</th>
      <th>Endereco</th>
      <th>Bairro</th>
      <th>Local trabalho</th>
      <th>Municipio</th>
      <th>Uf</th>
      <th>Regime juridico</th>
      <th>Cargo funcao</th>
      <th>Rg</th>
      <th>Cpf</th>
      <th>Email</th>
      <th>Contato</th>
      <th>Responsavel</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @inscriptions.each do |inscription| %>
      <tr>
        <td><%= inscription.nome %></td>
        <td><%= inscription.endereco %></td>
        <td><%= inscription.bairro %></td>
        <td><%= inscription.local_trabalho %></td>
        <td><%= inscription.municipio %></td>
        <td><%= inscription.uf %></td>
        <td><%= inscription.regime_juridico %></td>
        <td><%= inscription.cargo_funcao %></td>
        <td><%= inscription.rg %></td>
        <td><%= inscription.cpf %></td>
        <td><%= inscription.email %></td>
        <td><%= inscription.contato %></td>
        <td><%= inscription.responsavel %></td>
        <td><%= link_to 'Show', inscription %></td>
        <td><%= link_to 'Edit', edit_inscription_path(inscription) %></td>
        <td><%= link_to 'Destroy', inscription, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Inscription', new_inscription_path %>

app/views/inscriptions/new.html.erb
<h1>New Inscription</h1>

<%= render 'form', inscription: @inscription %>

<%= link_to 'Back', inscriptions_path %>

app/views/inscriptions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nome:</strong>
  <%= @inscription.nome %>
</p>

<p>
  <strong>Endereco:</strong>
  <%= @inscription.endereco %>
</p>

<p>
  <strong>Bairro:</strong>
  <%= @inscription.bairro %>
</p>

<p>
  <strong>Local trabalho:</strong>
  <%= @inscription.local_trabalho %>
</p>

<p>
  <strong>Municipio:</strong>
  <%= @inscription.municipio %>
</p>

<p>
  <strong>Uf:</strong>
  <%= @inscription.uf %>
</p>

<p>
  <strong>Regime juridico:</strong>
  <%= @inscription.regime_juridico %>
</p>

<p>
  <strong>Cargo funcao:</strong>
  <%= @inscription.cargo_funcao %>
</p>

<p>
  <strong>Rg:</strong>
  <%= @inscription.rg %>
</p>

<p>
  <strong>Cpf:</strong>
  <%= @inscription.cpf %>
</p>

<p>
  <strong>Email:</strong>
  <%= @inscription.email %>
</p>

<p>
  <strong>Contato:</strong>
  <%= @inscription.contato %>
</p>

<p>
  <strong>Responsavel:</strong>
  <%= @inscription.responsavel %>
</p>

<%= link_to 'Edit', edit_inscription_path(@inscription) %> |
<%= link_to 'Back', inscriptions_path %>